#!/bin/sh

PPNG_SERVER="https://ppng.io/"
RANDOM_STRING=$(echo $RANDOM | md5sum | head -c 20; echo;)

PPNG_URL="${PPNG_SERVER}/${RANDOM_STRING}"

target="$(realpath .)"

while true; do
	p="$prompt"
	[ -z "$p" ] && p="$target"
	sel="$(ls -1a "$target" |grep -v '^\.$' | dmenu -p "$p" -l 25 "$@" )"
	ec=$?
	[ "$ec" -ne 0 ] && exit $ec

	c="$(echo "$sel" |cut -b1)"
	if [ "$c" = "/" ]; then
		newt="$sel"
	else
		newt="$(realpath "${target}/${sel}")"
	fi

	if [ -e "$newt" ]; then
		target="$newt"
		if [ ! -d "$target" ]; then
            		echo $PPNG_URL | xclip -sel clip
            		timeout 30m cat $target | curl --header "Content-Disposition:attachment; filename="${sel}"" -T - "$PPNG_URL"
			exit 0
		fi
	fi
done
